/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xu_jnicallbackdemo_JNI */

#ifndef _Included_com_xu_jnicallbackdemo_JNI
#define _Included_com_xu_jnicallbackdemo_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xu_jnicallbackdemo_JNI
 * Method:    callbackvoidmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xu_jnicallbackdemo_JNI_callbackvoidmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_xu_jnicallbackdemo_JNI
 * Method:    callbackintmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xu_jnicallbackdemo_JNI_callbackintmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_xu_jnicallbackdemo_JNI
 * Method:    callbackStringmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xu_jnicallbackdemo_JNI_callbackStringmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_xu_jnicallbackdemo_JNI
 * Method:    callbackShowToast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xu_jnicallbackdemo_JNI_callbackShowToast
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
